const tableData = [
  {
    name: "Marcus Brown",
    email: "marcus@paystack.com",
    date: "01 Feb 2023",
    time: "04:55 PM",
    location: "Lagos, Nigeria",
    device: "MacOS, Safari",
    timeSpent: "02:54s",
    percentage: "90",
    bg: "mid-blue-bg",
  },
  {
    name: "Cynthia Jobs",
    email: "cynthia@microsoft.com",
    date: "29 Jan 2023",
    time: "11:40 AM",
    location: "Boston, US",
    device: "iOS, Chrome",
    timeSpent: "08:33s",
    percentage: "84",
    bg: "purple-bg",
  },
  {
    name: "Stephen Nelly",
    email: "stephen@facebook.com",
    date: "22 Jan 2023",
    time: "09:33 PM",
    location: "San Francisco, US",
    device: "Windows, Arc",
    timeSpent: "11:43s",
    percentage: "50",
    bg: "orange-bg",
  },
  {
    name: "Randy George",
    email: "randy@apple.com",
    date: "22 Jan 2023",
    time: "08:11 PM",
    location: "Cupertino, US",
    device: "MacOS, Arc",
    timeSpent: "13:15s",
    percentage: "70",
    bg: "turtle-green-bg",
  },
  {
    name: "Cheyenne Saris",
    email: "cheyenne.saris@ge.com",
    date: "18 Jan 2023",
    time: "04:33 AM",
    location: "Berlin, Germany",
    device: "Windows, Brave",
    timeSpent: "101:34s",
    percentage: "10",
    bg: "deep-cove-bg",
  },
];

export default tableData;
